apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  lockObjectName: kube-scheduler
  lockObjectNamespace: kube-system
  renewDeadline: 10s
  resourceLock: endpoints
  retryPeriod: 2s
profiles:
- schedulerName: default-scheduler
- schedulerName: bin-packing-scheduler
  plugins:
    preFilter:
      enabled:
      - name: "sample-plugin"
    filter:
      enabled:
      - name: "sample-plugin"
    preBind:
      enabled:
      - name: "sample-plugin"
  pluginConfig:
    - name: "sample-plugin"
      args:
        favorite_color: "#326CE5"
        favorite_number: 7
        thanks_to: "thockin"